// <auto-generated />
namespace HelendoWebK204.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ProTotalAmount : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProTotalAmount));
        
        string IMigrationMetadata.Id
        {
            get { return "202011281154343_ProTotalAmount"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
